### ISSUE TITLE
Logic behind refreshing interval of all states (too slow)

### ISSUE THREAD

**Issue by linchen4000** [Zefau/ioBroker.roomba#19] opened 2019-05-15 21:33 UTC
* Roomba Model: 980 & 675
* Roomba Software Version: latest (both)

Hi, 
my Roomba 675 has no sensor which can measure whether the bin is full, so I wrote myself a script.

A measure the time the roomba is running over the status state, and trigger my "bin Is full" state after a few hours of running. So far so good.

After my "bin is full", I would also like to have the opportunity to reset this state back to "bin is empty". That's not possible currently.

A had the idea to look at the state "binInserted" of this adapter. If it's changing to false, I had emptied the bin.

That would be nice and logically. But the adapter refreshes the states too rarely. I noticed it's updating every 60 - 66 seconds. (Tracked over refreshedDateTime)

In general I'm faster than one minute to empty the bin, and the state "binInserted" will stay on true, although I removed the bin of the roomba, emptied it and inserted it again.

Could you please provide an option to raise the refreshing interval? Or maybe make it configurable to fast / medium / rare or even an option to set the interval in seconds by the user.

It would be nice, if it's frequently enough that my script is working well. 
Thanks for your work.
Best regards from Hamburg

**Comment by Zefau** [comment] 2019-05-15 21:43
Thanks for the request. I will have a look at this tomorrow.

**Comment by Zefau** [comment] 2019-05-15 21:51
@linchen4000 just wondering: the adapter actually offers to reduce the refresh period in the settings (`Refresh time (in sec.) preferences will be retrieved from robot`). The standard is 60 seconds. Have you tried that?

**Comment by linchen4000** [comment] 2019-05-15 22:38
Oh...
 I didn't even know there was a possibility to scroll down there in the settings.
Well, that's almost a little embarrassing. Thanks, thats exactly what I was loocking for.

But maybe you can move the "other" settings tab a little bit higher.
At the moment it looks such as if nothing more would come under the authentication because of the large gap.

**Comment by Zefau** [comment] 2019-05-16 06:59
What's the browser you're on? Looks like this to me:

![Screenshot_2019-05-16 instances - ioBroker](https://user-images.githubusercontent.com/14368811/57832854-e8818180-77b8-11e9-8530-c5ed0f5ea92b.png)

**Comment by linchen4000** [comment] 2019-05-16 08:04
![roomba1](https://user-images.githubusercontent.com/29523683/57836848-df48e280-77c1-11e9-9793-f0de9ca3fd73.png)
![roomba2](https://user-images.githubusercontent.com/29523683/57836849-df48e280-77c1-11e9-922d-935157c17e84.png)

**Comment by linchen4000** [comment] 2019-05-16 08:04
I'm running Chrome on a 4K Display.

**Comment by Zefau** [comment] 2019-05-16 08:50
I can reproduce this with Chrome (even though it's not a 4k display ;-D). I'll fix this soon then.

**Comment by Zefau** [comment] 2019-05-16 09:08
fixed with v1.0.1

**Closed as completed by Zefau** 2019-05-16 09:08 UTC
Labels: enhancement
